hydra:
  run:
    dir: ${base_dir}

defaults:
  - _self_
  - model: null
  - encoder: wav2vec2_base
  - decoder: conv
  - slicer: null
  - data: null
  - contrastive: null

launch:
  init: false  # If true, write config to experiment dir and return
  test_run: false  # If true, run a quick test of the training loop
  dry_run: false  # If true, write checkpoints to /tmp
  train: true
  accelerator: auto
  resume: false  # Resume training from last checkpoint in storage_dir

# Database to use for training and validation
databases:
  nisqa:
    factory: local_sqa.modules.data_loader.ParquetParser
    input_path: ../data/parquet/nisqa  # Default path to the parquet shards
    train_dataset_names: train_sim
    val_dataset_names: val_sim
    disable_validation_reshuffle: true
    additional_keys:
      - rating
  bvcc:
    factory: local_sqa.modules.data_loader.ParquetParser
    input_path: ../data/parquet/bvcc
    train_dataset_names: train_main
    val_dataset_names: val_main
    disable_validation_reshuffle: true
    additional_keys:
      - rating

train_dataloader:
  factory: local_sqa.modules.data_loader.Dataloader
  batch_size: 64
  max_total_size: ${max_total_size}
  max_padding_rate: 0.1
  shuffle_buffer_size: ${eval:"10*${train_dataloader.batch_size}"}
  num_workers: -1
val_dataloader:
  factory: local_sqa.modules.data_loader.Dataloader
  batch_size: 64
  stage: val
  max_total_size: ${max_total_size}
  max_padding_rate: 0.1
  reshuffle: false
  num_workers: -1
  seed: 0

# Validation metric to monitor for learning rate scheduling and early stopping
validation:
  metric: SRCC
  maximize: true
  n_back_off: 0
  lr_update_factor: 3.33e-1
  back_off_patience: null

base_dir: ../../exp
lr: 1e-4
min_lr: 1e-6
num_seeds: 100
sub_iterator_length: 400
zero_init: false

trainer:
  storage_dir: null
  stop_trigger:  # Stop training after this number of iterations/epochs
  - 100
  - "epoch"
  summary_trigger:  # Write summaries to tensorboard after this number of iterations/epochs
  - 1_000
  - "iteration"
  checkpoint_trigger:  # Write a checkpoint after this number of iterations/epochs
  - 1
  - "epoch"
  optimizer:
    factory: padertorch.optimizer.Adam
    lr: ${lr}
    gradient_clipping: 10.
  model:
    factory: local_sqa.models.ssl_mos.SSLMOS
    proj_in_size: ${proj_in_size}
    shift: 0.
    scale: 1.
    target_key: rating.mean
    normalize_ratings: true
    out_activation: tanh
    standardize_audio: true
    equal_loudness: true
    l2_normalization: true
    criterion:
      factory: torch.nn.L1Loss
      reduction: none
    loss_weights:
      regression: 1.
      contrastive_loss: 1.
      consistency_loss_emb: 10.
      consistency_loss_scores: 1.
      frame_regression: 0.
